/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ArrayRelationInsertSchema struct {
	// The name of the array relationship over which the related rows must be inserted
	Relationship string `json:"relationship"`

	Type_ string `json:"type"`
}
