/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RelationshipType string

// List of RelationshipType
const (
	OBJECT RelationshipType = "object"
	ARRAY RelationshipType = "array"
)
