/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InsertMutationOperation struct {

	PostInsertCheck *Expression `json:"post_insert_check,omitempty"`
	// The fields to return for the rows affected by this insert operation
	ReturningFields map[string]Field `json:"returning_fields,omitempty"`
	// The rows to insert into the table
	Rows []map[string]Object `json:"rows"`

	Table *[]string `json:"table"`

	Type_ string `json:"type"`
}
