/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ColumnTypeArray struct {

	ElementType *ColumnType `json:"element_type"`

	Nullable bool `json:"nullable"`

	Type_ string `json:"type"`
}
