/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QueryResponse struct {
	// The results of the aggregates returned by the query
	Aggregates map[string]ModelMap `json:"aggregates,omitempty"`
	// The rows returned by the query, corresponding to the query's fields
	Rows []map[string]Object `json:"rows,omitempty"`
}
