/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TableInsertSchema struct {
	// The fields that will be found in the insert row data for the table and the schema for each field
	Fields map[string]InsertFieldSchema `json:"fields"`
	// The names of the columns that make up the table's primary key
	PrimaryKey []string `json:"primary_key,omitempty"`

	Table *[]string `json:"table"`
}
