/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Query struct {
	// Aggregate fields of the query
	Aggregates map[string]Aggregate `json:"aggregates,omitempty"`
	// Optionally limit the maximum number of rows considered while applying aggregations. This limit does not apply to returned rows.
	AggregatesLimit float64 `json:"aggregates_limit,omitempty"`
	// Fields of the query
	Fields map[string]Field `json:"fields,omitempty"`
	// Optionally limit the maximum number of returned rows. This limit does not apply to records considered while apply aggregations.
	Limit float64 `json:"limit,omitempty"`
	// Optionally offset from the Nth result. This applies to both row and aggregation results.
	Offset float64 `json:"offset,omitempty"`

	OrderBy *OrderBy `json:"order_by,omitempty"`

	Where *Expression `json:"where,omitempty"`
}
