/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MutationRequest struct {
	// The schema by which to interpret row data specified in any insert operations in this request
	InsertSchema []TableInsertSchema `json:"insert_schema"`
	// The mutation operations to perform
	Operations []MutationOperation `json:"operations"`
	// The relationships between tables involved in the entire mutation request
	TableRelationships []TableRelationships `json:"table_relationships"`
}
