/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// AtomicitySupportLevel : Describes the level of transactional atomicity the agent supports for mutation operations. 'row': If multiple rows are affected in a single operation but one fails, only the failed row's changes will be reverted 'single_operation': If multiple rows are affected in a single operation but one fails, all affected rows in the operation will be reverted 'homogeneous_operations': If multiple operations of only the same type exist in the one mutation request, a failure in one will result in all changes being reverted 'heterogeneous_operations': If multiple operations of any type exist in the one mutation request, a failure in one will result in all changes being reverted 
type AtomicitySupportLevel string

// List of AtomicitySupportLevel
const (
	ROW AtomicitySupportLevel = "row"
	SINGLE_OPERATION AtomicitySupportLevel = "single_operation"
	HOMOGENEOUS_OPERATIONS AtomicitySupportLevel = "homogeneous_operations"
	HETEROGENEOUS_OPERATIONS AtomicitySupportLevel = "heterogeneous_operations"
)
