/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ColumnField struct {

	Column string `json:"column"`

	ColumnType string `json:"column_type"`

	Type_ string `json:"type"`
}
