/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InsertCapabilities struct {
	// Whether or not nested inserts to related tables are supported
	SupportsNestedInserts bool `json:"supports_nested_inserts,omitempty"`
}
