/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderByRelation struct {
	// Further relationships to follow from the relationship's target table. The key of the map is the relationship name.
	Subrelations map[string]OrderByRelation `json:"subrelations"`

	Where *Expression `json:"where,omitempty"`
}
