/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApplyBinaryArrayComparisonOperator struct {

	Column *ComparisonColumn `json:"column"`

	Operator *BinaryArrayComparisonOperator `json:"operator"`

	Type_ string `json:"type"`

	ValueType string `json:"value_type"`

	Values []ModelMap `json:"values"`
}
