/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Capabilities struct {

	Comparisons *ComparisonCapabilities `json:"comparisons,omitempty"`

	DataSchema *DataSchemaCapabilities `json:"data_schema,omitempty"`

	Datasets *Object `json:"datasets,omitempty"`

	Explain *Object `json:"explain,omitempty"`

	Licensing *Object `json:"licensing,omitempty"`

	Metrics *Object `json:"metrics,omitempty"`

	Mutations *MutationCapabilities `json:"mutations,omitempty"`

	Queries *QueryCapabilities `json:"queries,omitempty"`

	Raw *Object `json:"raw,omitempty"`

	Relationships *Object `json:"relationships,omitempty"`

	ScalarTypes *map[string]ScalarTypeCapabilities `json:"scalar_types,omitempty"`

	Subscriptions *Object `json:"subscriptions,omitempty"`

	UserDefinedFunctions *Object `json:"user_defined_functions,omitempty"`
}
