/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ObjectRelationInsertSchema struct {

	InsertionOrder *ObjectRelationInsertionOrder `json:"insertion_order"`
	// The name of the object relationship over which the related row must be inserted
	Relationship string `json:"relationship"`

	Type_ string `json:"type"`
}
