/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OpenApiXml struct {

	Attribute bool `json:"attribute,omitempty"`

	Name string `json:"name,omitempty"`

	Namespace string `json:"namespace,omitempty"`

	Prefix string `json:"prefix,omitempty"`

	Wrapped bool `json:"wrapped,omitempty"`
}
