/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FunctionInformationArgument struct {
	// The name of the argument
	Name string `json:"name"`
	// If the argument can be omitted
	Optional bool `json:"optional,omitempty"`

	Type_ string `json:"type"`
}
