/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GraphQLType string

// List of GraphQLType
const (
	INT_ GraphQlType = "Int"
	FLOAT GraphQlType = "Float"
	STRING_ GraphQlType = "String"
	BOOLEAN GraphQlType = "Boolean"
	ID GraphQlType = "ID"
)
