/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Expression struct {
    ApplyBinaryComparisonOperator
    NotExpression
    ExistsExpression
    OrExpression
    ApplyBinaryArrayComparisonOperator
    ApplyUnaryComparisonOperator
    AndExpression
}
