/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExplainResponse struct {
	// Lines of the formatted explain plan response
	Lines []string `json:"lines"`
	// The generated query - i.e. SQL for a relational DB
	Query string `json:"query"`
}
