/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FunctionType string

// List of FunctionType
const (
	READ FunctionType = "read"
	WRITE FunctionType = "write"
)
