/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OpenApiDiscriminator struct {

	Mapping map[string]string `json:"mapping,omitempty"`

	PropertyName string `json:"propertyName"`
}
