/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelMap interface{}

type Object interface{}

type ScalarType interface{}

type GraphQlType string

type ScalarValueComparison struct {

	Type_ string `json:"type"`

	Value ModelMap `json:"value"`

	ValueType string `json:"value_type"`
}
