/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ComparisonColumn struct {

	ColumnType string `json:"column_type"`
	// The name of the column
	Name string `json:"name"`
	// The path to the table that contains the specified column. Missing or empty array means the current table. [\"$\"] means the query table. No other values are supported at this time.
	Path []string `json:"path,omitempty"`
}
