/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OpenApiExternalDocumentation struct {

	Description string `json:"description,omitempty"`

	Url string `json:"url"`
}
