/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderBy struct {
	// The elements to order by, in priority order
	Elements []OrderByElement `json:"elements"`
	// A map of relationships from the current query table to target tables. The key of the map is the relationship name. The relationships are used within the order by elements.
	Relations map[string]OrderByRelation `json:"relations"`
}
