/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FunctionInfo struct {
	// argument info - name/types
	Args []FunctionInformationArgument `json:"args"`
	// Description of the table
	Description string `json:"description,omitempty"`

	Name *[]string `json:"name"`
	// object response if false, rows if true
	ResponseCardinality string `json:"response_cardinality"`

	Returns *FunctionReturnType `json:"returns"`

	Type_ *FunctionType `json:"type"`
}
