/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Capabilities of a scalar type. comparison_operators: The comparison operators supported by the scalar type. aggregate_functions: The aggregate functions supported by the scalar type. update_column_operators: The update column operators supported by the scalar type. graphql_type: Associates the custom scalar type with one of the built-in GraphQL scalar types.  If a `graphql_type` is specified then HGE will use the parser for that built-in type when parsing values of the custom type. If not given then any JSON value will be accepted. 
type ScalarTypeCapabilities struct {

	AggregateFunctions *map[string]string `json:"aggregate_functions,omitempty"`

	ComparisonOperators *map[string]string `json:"comparison_operators,omitempty"`

	GraphqlType *GraphQlType `json:"graphql_type,omitempty"`

	UpdateColumnOperators *map[string]UpdateColumnOperatorDefinition `json:"update_column_operators,omitempty"`
}
