/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ObjectRelationInsertionOrder string

// List of ObjectRelationInsertionOrder
const (
	BEFORE_PARENT ObjectRelationInsertionOrder = "before_parent"
	AFTER_PARENT ObjectRelationInsertionOrder = "after_parent"
)
