/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NestedObjField struct {

	Column string `json:"column"`

	Query *Query `json:"query"`

	Type_ string `json:"type"`
}
