/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubqueryComparisonCapabilities struct {
	// Does the agent support comparisons that involve related tables (ie. joins)?
	SupportsRelations bool `json:"supports_relations,omitempty"`
}
