/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SchemaResponse struct {
	// Available functions
	Functions []FunctionInfo `json:"functions,omitempty"`
	// Object type definitions referenced in this schema
	ObjectTypes []ObjectTypeDefinition `json:"objectTypes,omitempty"`
	// Available tables
	Tables []TableInfo `json:"tables"`
}
