/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorResponseType string

// List of ErrorResponseType
const (
	UNCAUGHT_ERROR ErrorResponseType = "uncaught-error"
	MUTATION_CONSTRAINT_VIOLATION ErrorResponseType = "mutation-constraint-violation"
	MUTATION_PERMISSION_CHECK_FAILURE ErrorResponseType = "mutation-permission-check-failure"
)
