/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RawResponse struct {
	// The rows returned by the raw query.
	Rows []map[string]ModelMap `json:"rows"`
}
