/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TableRequest struct {
	// If present, a list of columns and values for the columns that the query must be repeated for, applying the column values as a filter for each query.
	Foreach []map[string]ScalarValue `json:"foreach,omitempty"`

	Query *Query `json:"query"`

	Table *[]string `json:"table"`
	// The relationships between tables involved in the entire query request
	TableRelationships []Relationships `json:"table_relationships"`

	Type_ string `json:"type"`
}
