/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderByTarget struct {
    OrderBySingleColumnAggregate
    OrderByColumn
    OrderByStarCountAggregate
}
