/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderByElement struct {

	OrderDirection *OrderDirection `json:"order_direction"`

	Target *OrderByTarget `json:"target"`
	// The relationship path from the current query table to the table that contains the target to order by. This is always non-empty for aggregate order by targets
	TargetPath []string `json:"target_path"`
}
