/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NamedArgument struct {
	// The name of the named argument
	Name string `json:"name"`

	Type_ string `json:"type"`

	Value *ArgumentValue `json:"value"`
}
