/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExistsExpression struct {

	InTable *ExistsInTable `json:"in_table"`

	Type_ string `json:"type"`

	Where *Expression `json:"where"`
}
