/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataSchemaCapabilities struct {

	ColumnNullability *ColumnNullability `json:"column_nullability,omitempty"`
	// Whether tables can have foreign keys
	SupportsForeignKeys bool `json:"supports_foreign_keys,omitempty"`
	// Whether tables can have primary keys
	SupportsPrimaryKeys bool `json:"supports_primary_keys,omitempty"`
	// Whether the database supports tables with no defined schema
	SupportsSchemalessTables bool `json:"supports_schemaless_tables,omitempty"`
}
