/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ScalarValue struct {

	Value ModelMap `json:"value"`

	ValueType string `json:"value_type"`
}
