/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NestedArrayField struct {

	Field *Field `json:"field"`
	// Optionally limit the maximum number of returned elements of the array
	Limit float64 `json:"limit,omitempty"`
	// Optionally skip the first n elements of the array
	Offset float64 `json:"offset,omitempty"`

	OrderBy *OrderBy `json:"order_by,omitempty"`

	Type_ string `json:"type"`

	Where *Expression `json:"where,omitempty"`
}
