/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FunctionRequest struct {

	Function *[]string `json:"function"`
	// Function Arguments. TODO. Improve this.
	FunctionArguments []FunctionRequestArgument `json:"function_arguments,omitempty"`

	Query *Query `json:"query"`
	// The relationships between entities involved in the entire query request
	Relationships []Relationships `json:"relationships"`

	Type_ string `json:"type"`
}
