/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ObjectTypeDefinition struct {
	// The columns of the type
	Columns []ColumnInfo `json:"columns"`
	// The description of the type
	Description string `json:"description,omitempty"`
	// The name of the type
	Name string `json:"name"`
}
