/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Constraint struct {
	// The columns on which you want want to define the foreign key.
	ColumnMapping map[string]string `json:"column_mapping"`

	ForeignTable *[]string `json:"foreign_table"`
}
