/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ColumnNullability string

// List of ColumnNullability
const (
	ONLY_NULLABLE ColumnNullability = "only_nullable"
	NULLABLE_AND_NON_NULLABLE ColumnNullability = "nullable_and_non_nullable"
)
