/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Relationship struct {
	// A mapping between columns on the source table to columns on the target table
	ColumnMapping map[string]string `json:"column_mapping"`

	RelationshipType *RelationshipType `json:"relationship_type"`

	TargetTable *[]string `json:"target_table"`
}
