/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TableType string

// List of TableType
const (
	TABLE TableType = "table"
	VIEW TableType = "view"
)
