/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OpenApiSchema struct {

	AdditionalProperties map[string]Object `json:"additionalProperties,omitempty"`

	AllOf []OneOfOpenApiSchemaAllOfItems `json:"allOf,omitempty"`

	AnyOf []OneOfOpenApiSchemaAnyOfItems `json:"anyOf,omitempty"`

	Default_ *Object `json:"default,omitempty"`

	Deprecated bool `json:"deprecated,omitempty"`

	Description string `json:"description,omitempty"`

	Discriminator *OpenApiDiscriminator `json:"discriminator,omitempty"`

	Enum []Object `json:"enum,omitempty"`

	Example *Object `json:"example,omitempty"`

	ExclusiveMaximum bool `json:"exclusiveMaximum,omitempty"`

	ExclusiveMinimum bool `json:"exclusiveMinimum,omitempty"`

	ExternalDocs *OpenApiExternalDocumentation `json:"externalDocs,omitempty"`

	Format string `json:"format,omitempty"`

	Items *OneOfOpenApiSchemaItems `json:"items,omitempty"`

	MaxItems int32 `json:"maxItems,omitempty"`

	MaxLength int32 `json:"maxLength,omitempty"`

	MaxProperties int32 `json:"maxProperties,omitempty"`

	Maximum float64 `json:"maximum,omitempty"`

	MinItems int32 `json:"minItems,omitempty"`

	MinLength int32 `json:"minLength,omitempty"`

	MinProperties int32 `json:"minProperties,omitempty"`

	Minimum float64 `json:"minimum,omitempty"`

	MultipleOf float64 `json:"multipleOf,omitempty"`

	Not *OneOfOpenApiSchemaNot `json:"not,omitempty"`

	Nullable bool `json:"nullable,omitempty"`

	OneOf []OneOfOpenApiSchemaOneOfItems `json:"oneOf,omitempty"`

	Pattern string `json:"pattern,omitempty"`

	Properties map[string]Object `json:"properties,omitempty"`

	ReadOnly bool `json:"readOnly,omitempty"`

	Required []string `json:"required,omitempty"`

	Title string `json:"title,omitempty"`

	Type_ string `json:"type,omitempty"`

	UniqueItems bool `json:"uniqueItems,omitempty"`

	WriteOnly bool `json:"writeOnly,omitempty"`

	Xml *OpenApiXml `json:"xml,omitempty"`
}
