/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateMutationOperation struct {

	PostUpdateCheck *Expression `json:"post_update_check,omitempty"`
	// The fields to return for the rows affected by this update operation
	ReturningFields map[string]Field `json:"returning_fields,omitempty"`

	Table *[]string `json:"table"`

	Type_ string `json:"type"`
	// The updates to make to the matched rows in the table
	Updates []RowUpdate `json:"updates"`

	Where *Expression `json:"where,omitempty"`
}
