/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorResponse struct {
	// Error details
	Details ModelMap `json:"details,omitempty"`
	// Error message
	Message string `json:"message"`

	Type_ *ErrorResponseType `json:"type,omitempty"`
}
